### ISSUE TITLE
Manually triggered validation with validationSchema of nested field inside FieldArray is returns empty object

### ISSUE THREAD

**Issue by MatviiStelmakh** [formium/formik#1084]
## 🐛 Bug report
Manually trigerred nested field validation inside FieldArray is not working

### Current Behavior
After click on Validate button error for field email is empty object instead of string "Email is required"

### Expected behavior
Should fill correct error for field inside errors object like in case of blur

### Reproducible example
https://codesandbox.io/s/vm3nrq3zr0

**Comment by MatthiasMargot** [comment]
So I've taken a peek at the codebase and it seems that the reason this is not working is because calling the formikAction `validateField` triggers an attempt at validating the field based on the `validate` prop passed to the `<Field />` in question.

This results in an illegal invocation type error given that the `validate` prop was not provided.

A possible fix to this would be to first look for the `validate` prop on the field in question and on lookup failure to fall back on the provided `validationSchema` or `validate` function provided to formik directly. (I'm not entirely sure it's possible to extract a field-validation back out of a provided `yup` validation schema so this might involve validating the whole schema and then filtering the errors for just the field that was requested for validation, this is especially true for the fallback to the top-level `validate` function)

Is this field-level to top-level fallback desired behaviour?

If so, I'll take a jab at solving it and open a PR with it.

Let me know your thoughts on this @jaredpalmer since this does not necessarily seem like a semantic bug.

**Comment by angeloreale** [comment]
@MatthiasMargot I think a fallback to the top-level validate function would be ideal. Would avoid a lot of redundancy and create a simple mean to imperatively validate a field without necessarily having to duplicate the validation scheme for that field.

**Comment by NathanHealea** [comment]
@MatthiasMargot In order to use top-level validation you would have to call `validateForm` to trigger the `validateSchema`? Wouldn't that cause any field with **_required_** validation to show a validation error even though the user may not have gotten to those input fields?

**Comment by johnrom** [comment]
Related #1755

**Comment by maddhruv** [comment]
Closing as duplicate
