### ISSUE TITLE
Post render callback

### ISSUE THREAD

**Issue by brokarth** [formium/formik#1195]
## ❓Question
Hello, I got a question, I need to know if there is a post-render callback on formik, I got a button that is outside of the form, so to enable or disable the button, I send a event from the form saying if the form is valid.

I tried using validate function, but it is executed before the forms knows if is valid or not
so i put it on the render function, but react warning me that i execute a state change inside render function (which is right since I'm changing the disable prop of the submit button with a event sent from the form render

I tried putting the function on the `componentDidUpdate`, but it is not called when something change on the form

Why i cannot use the validate function? because each field knows how to validate it self, I need this because the form is built dynamically

**Comment by jaredpalmer** [comment]
Can you create a codesandbox demonstrating what you are trying to do? Or share some code?

**Comment by brokarth** [comment]
Sure, ill create the repo and tell you when is done

**Comment by garyng2000** [comment]
throw away the rulebook of 'pure' , something like below(may need setTimeout but you get the idea)
the key is do use this.setState(), use instance variable. if you must use setState, probably have to it via setTimeout to get around React's protection. Treat setTimeout as external event not trigger by click but timer(no different than manually click a button to disable something).

stealErrorInfo=(errors)=>{this.buttonDisable = errors.isempty}
<Formik
render={({errors})=>
(
<Form>

{this.stealErrorInfo(errors)}
</Form>
)} />
<button disable={this.buttonDisabled}/>

**Comment by brokarth** [comment]
Thanks for the answer but i dont think is good solution.

Here is a repo with the warning for you to see:
https://gitlab.com/brokarth/formik-post-validation-callback

I n the README is the instructions for replicate the problem, if you got any question, tell me :)

**Comment by garyng2000** [comment]
that is exactly what I meant 'throw away the 'pure' rulebook' :-)
you can only get the errors list of Formik during rendering so unless your button is under its context, you cannot see it. what I suggest is to 'steal' it(which is effectively your post render callback)
whether it is a good solution or not is up to you to decide. just make sure that if you must setState rather than using simple instance variable, it needs to be stopped or else it becomes
render -> delay change state(which trigger render)->render ....


the setTimeout would trick React thinking you are doing it as 'pure' even though you are not.

**Comment by brokarth** [comment]
I understand what you say, but since we have already a workaround, I don't think that an `setTimeOut` is a good solution. I would like a definitive solution.

So, it appear that formik doesn't have a post render callback to know the form state at that point... so we can may build it.

So i think in two options:

1. As a developer I would love to call to `componentDidUpdate` since is more redeable and a better approach to react way. But it doesn't work, i guess is because the component that is actually updating is the `<Foirmik />` and not my `<MySuperForm />`. Is there a way to call `componentDidUpdate` from the child to the parent? is it valid from the react perspective? is it a good approach?
2. Another approach is to create a postRender callback in formik that gives you access to the context, again, is it a good approach? how the performance will be impacted?

What do you think?

**Comment by garyng2000** [comment]
What you want is 'PreRender' from the formik perspective not PostRender because you want to pass the formik bag info to context outside Formik and your 'button' can be before or after the Formik block and React as a renderer which still process the whole component in the layout order, it needs to pass this on before the rendering.
Currently, you can only steal it during formik rendering which can be used either through instance variable(visible in the same rendering round for element after the formik block but not before) or must use the setTimeOut trick to basically render it again with the revised formik bag value stolen.
Doing it in 'componentDidUpdate' is basically the same(depending in change detected in the Formik bag, re-render it one more time). But just make sure it would not be a endless loop

So yes, pre-render hook is the best but even React is discouraging new code to use that(they are deprecating componentWillUpdate. I don't know why though). This seems to be a frequently needed options in many cases but may be they have their reasons.

What do you mean by componentDidUpdate doesn't work ? Not sure how you do it.

**Comment by brokarth** [comment]
If move the [`checkFormValidity`](https://gitlab.com/brokarth/formik-post-validation-callback/blob/master/pages/my-super-form.jsx#L31) call inside a `componentDidUpdate` function on  [`<MySuperForm />`](https://gitlab.com/brokarth/formik-post-validation-callback/blob/master/pages/my-super-form.jsx), it is never called.

And as i say, it makes sense since the component that is updating is `<Formik />`, and not `<MySuperForm />`.

I need to know the form state after validations are done, if it is done before or after the render call i really don't care, but for good practices i think i will have a more consistent state after the render.

**Comment by maddhruv** [comment]
Closing due to long inactivity
