### ISSUE TITLE
Write Migration Guide

### ISSUE THREAD

**Issue by jaredpalmer** [formium/formik#1630]
## Breaking Changes
- Resolve instead of throw errors from async validate #1575 
- `resetForm(values: Values): void` -> `resetForm(initialState: Partial<FormikState<Values>>)`

## Deprecations
- Field render

**Comment by VehpuS** [comment]
Small suggestion - use a version of DeepPartial instead of Partial for resetForm's initial value. I found it is very useful for forms managing complex data structures (i.e. nested graphql types).

Some possible versions:
- https://stackoverflow.com/questions/45372227/how-to-implement-typescript-deep-partial-mapped-type-not-breaking-array-properti/49936686#49936686
- https://github.com/krzkaczor/ts-essentials

Thanks for this awesome library btw :)

**Comment by maddhruv** [comment]
Closing due to long inactivity
