### ISSUE TITLE
[v2] Rewrite part/all <Formik /> docs with useFormik and FromikContext or analogs

### ISSUE THREAD

**Issue by PetroPavlenko** [formium/formik#1666]
## 📖 Documentation
I would like to start replacing `withFormik` HOC with `useFormik` Hook. But I need some more docs with `useFormik`. So I won't use internal methods.

**Comment by sw-yx** [comment]
```tsx
import React from 'react'
import { useFormik } from 'formik'

type Props = {
  label: string
  name: string
  type: string
  formik: {
    getFieldProps: ReturnType<typeof useFormik>['getFieldProps']
  }
}
const MyTextField = ({ label, formik, ...props }: Props) => {
  const [field, meta] = formik.getFieldProps(props)
  return (
    <>
      <label>
        {label}
        <input {...field} {...props} />
      </label>
      {meta.touched && meta.error ? <div className="error">{meta.error}</div> : null}
    </>
  )
}

const Example = () => {
  const formik = useFormik({
    initialValues: { email: '', firstName: 'red', lastName: '' },
    onSubmit: (values, actions) => {
      setTimeout(() => {
        alert(JSON.stringify(values, null, 2))
        actions.setSubmitting(false)
      }, 1000)
    },
  })
  return (
    <div>
      <h1>My Form</h1>
      <form onSubmit={formik.handleSubmit}>
        <MyTextField formik={formik} name="firstName" type="text" label="First Name" />
        <MyTextField formik={formik} name="lastName" type="text" label="Last Name" />
        <MyTextField formik={formik} name="email" type="email" label="Email" />
        <button type="submit">Submit</button>
      </form>
    </div>
  )
}
export default Example
```

**Comment by pmonty** [comment]
I read Jared said that useFormik would not be exported. I am dying for official documentation!

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by johnrom** [comment]
We will absolutely be updating the docs for useFormik and useFormikContext once we formalize the API in v3. v2's API using `useFormik` and `useFormikContext` isn't super performant, because it is a plain wrapper for React Context, which doesn't have many optimizations internally. However, no matter how the new API works I do not believe we'll be removing either of these methods, as from an API point of view they are the exact methods which achieve their given goals (using Formik's API itself without bindings to React's Context, and using Formik's React Context, respectively). However, in terms best practices, we may recommend using other methods when they are more performant, so formalizing the documentation will sadly have to wait. Those may include new broad hooks like `useFormikState` and `useFormikApi`, or highly specific hooks like 

```
const [values, setValues] = `useFormikValues()`;
const [touched, setTouched] = `useFormikTouched();`
```

The specifics of the API will be formalized with v3.
