### ISSUE TITLE
Confusing validate schema behavior

### ISSUE THREAD

**Issue by doomsower** [formium/formik#1697]
### Current Behavior

`validateYupSchema` casts empty strings to undefined. Moreover, it does so inconsistently (#1125, #1520)

### Expected behavior

I have a yup schema which treats empty strings and undefined values differently. I had to debug and found this out. So technically `validationSchema` prop is not strictly yup schema. Why is that so? Current workaround is to use your own `validateYupSchema` but without this casting.

### Suggested solution(s)

I think `validateYupSchema` should pass values to yup without alterations. Yup is totally capable of dealing with empty strings, undefined values and nulls on its own. Or at least this unexpected behavior should be mentioned in docs.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.0.1-rc.12
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by maddhruv** [comment]
Hey @doomsower can you try with the latest stable release, and if problem still persists, revert back so that we can help.

Closing for now

**Comment by burtek** [comment]
@maddhruv it does and is driving me crazy. Just spent 2 hrs trying to figure out why is `yup`'s schema saying a field that should be `.defined()` is invalid when in the same time I get that field as empty string in `validate={console.log}`.

It's because of `prepareDataForValidation` call in 1073:
https://github.com/formium/formik/blob/c45baba225d0e15b345021878b9af541c31d5a3b/packages/formik/src/Formik.tsx#L1067-L1078

which indeed casts empty strings to `undefined`:
https://github.com/formium/formik/blob/c45baba225d0e15b345021878b9af541c31d5a3b/packages/formik/src/Formik.tsx#L1083-L1106

This `prepareDataForValidation` function AFAIK is used only for `yup` validation, which is  SOOOOO wrong since `yup` can actually 
distinguish between `''` and `undefined` using `.required()` or `.defined()` - especially for TypeScript users.

**Comment by maddhruv** [comment]
I've raised a PR fixing the same - https://github.com/formium/formik/pull/2902
