### ISSUE TITLE
isValid incorrectly set to true after checkbox change

### ISSUE THREAD

**Issue by lnpbk** [formium/formik#1732]
## 🐛 Bug report

I'm not sure if this is a bug, or expected behaviour, but it caught me out when trying to disable a submit button when my form was invalid.

### Current Behavior

When toggling a boolean checkbox, an invalid form is has a `isValid` prop set to `true`. This only happens when `validateOnChange` is `false`

### Expected behavior

`isValid` should not be set to `true` upon checkbox state change

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-rykht

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.2
| React            | 16.5
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by maddhruv** [comment]
closing due to long in-activity. We would recommend you to migrate to 2.x and enjoy the benefits to using the new APIs and hooks.
Also, you can follow this example for more reference - https://codesandbox.io/s/formik-v2-tutorial-final-ge1pt?file=/src/index.js

More info on migrating - https://formik.org/docs/migrating-v2
