### ISSUE TITLE
Reset dirty state on successful submit

### ISSUE THREAD

**Issue by vishwam** [formium/formik#2110]
### Current Behavior

It's a very common scenario to show a confirmation prompt if the user accidentally exits out of a form with unsaved changes (e.g., by when they hit the back button or click on a link). The idiomatic way is rendering something like [React Router's Prompt](https://reacttraining.com/react-router/web/api/Prompt) if the form is dirty.

However, this requires the dirty state to be reset once the form has been saved successfully (since there are no more unsaved changes). The only way to do it right now is calling actions.resetForm({ values }) after submit, which seems redundant.

### Desired Behavior

Now that Formik knows when the submit function has fully finished, it can clear the dirty state after a successful complete.

### Suggested Solution

The `SUBMIT_SUCCESS` message sets the dirty state to `false`.

### Describe alternatives you've considered

Provide a different field (e.g., `unsaved`) that returns true if the form has unsaved changes.

**Comment by rodricarranza** [comment]
I have the exact same problem as @vishwam and this would be really helpful. IIRC the `dirty` state is set to **true** always taking as a reference the initial values provided. I have an editor that saves every X seconds and show the warning modal if the user tries to leave the page with unsaved changes => `dirty`.

**Comment by gffuma** [comment]
I'm recently face this issue.

The problem is that `dirty` is calculated vs the ref of `initialValues` instead of the the props `initialValues` as you can see here:

https://github.com/formium/formik/blob/4a0de5d15464fb553467c4962b6567e77c16c0c5/packages/formik/src/Formik.tsx#L971-L974

This because `resetForm` is intended to reset even the `initialValues` through its ref.

Yes, you can use `enableReinitialize` to keep `initialValues` updated but in an auto save scenario like the one described by @rodricarranza this cause issue because the new `initialValues` can override the current user input.

Yes, one possible solution is to *simply* implement yourself an equivalente version of `dirty` by deep comparing your values. The downside is that deep comparing is an expensive operation and if we can avoid using it twice would be nice.

**The workaround** 

There is an undocumented feature but available in **formik** since long time that enable `onReset` to be a promise and call the *dispatch function* after the promise.

https://github.com/formium/formik/blob/4a0de5d15464fb553467c4962b6567e77c16c0c5/packages/formik/src/Formik.tsx#L437-L438

If we combine `enableReinitialize` with this trick when `initialValues` changes we can update its ref but not the values.
Heres to you the `onReset` trick:

```js
// Combine it with enableReinitialize
export function onResetHackReinitializeToKeepDirtyUpdate(values, methods) {
  // Force update of formik (in the cheapest way)
  methods.setFormikState(state => ({ ...state }))
  // Prevent erasing values
  // https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L438
  const noopPromise = new Promise(() => {})
  return noopPromise
}
```

To show you all this things, i made a codesandbox:
https://codesandbox.io/s/silly-shamir-hmrmg

If you disable the `onReset` you can see that the values in some cases erase your input, on the other hand disable it make `dirty` not update with your provided `initialValues` at the end enable `onReset` *workaround* enable both `dirty` update and no erasing values simply when your values match your last saving value your have `dirty` se to **false**.

This is a workaround it would be cool if we can do this in a more cleaner way, an idea is to have a prop to tell **formik** to run the `dirty` memo against your prop instead of ref.

CC @jaredpalmer 



I hope this can hep you @vishwam @rodricarranza 😄

**Comment by rodricarranza** [comment]
Thanks for the codesandbox and the detailed description of the workaround @gffuma ! I wish I've known this before 😆 . I decided to not rely on `dirty` state for the auto-save feature. As you said, it would be great to have a cleaner way to solve this.

**Comment by maddhruv** [comment]
Closing as there's already a proposed workaround

**Comment by rscotten** [comment]
You can change `isDirty` to false after submitting by calling `resetForm({ values })`. Here's my save on blur implementation:

```typescript
import { Formik, Form } from 'formik';

<Formik>
  {({
    dirty,
    values,
    submitForm,
    resetForm,
  }: FormikProps<FormData>) => {
    return (
      <Form
        onBlur={async () => {
          if (dirty) {
            await submitForm();
            resetForm({ values }); // <-- Changes isDirty to false
          }
        }}
      >
        { /** form stuff */ }
      </Form>
    );
  }}
</Formik>
```

**Comment by metanveer** [comment]
> 
> 
> You can change `isDirty` to false after submitting by calling `resetForm({ values })`. Here's my save on blur implementation:
> 
> ```ts
> import { Formik, Form, FormikProps } from 'formik';
> 
> interface FormData {
>   // your form data
> }
> 
> <Formik>
>   {({
>     dirty,
>     values,
>     submitForm,
>     resetForm,
>   }: FormikProps<FormData>) => {
>     return (
>       <Form
>         onBlur={async () => {
>           if (dirty) {
>             await submitForm();
>             resetForm({ values }); // <-- Changes isDirty to false
>           }
>         }}
>       >
>         { /** form stuff */ }
>       </Form>
>     );
>   }}
> </Formik>
> ```

Wonderful solution! Thank you very much!!
