### ISSUE TITLE
Multiple issues on <Field /> doc page

### ISSUE THREAD

**Issue by patspam** [formium/formik#2434]
I'm seeing multiple issues here:

![image](https://user-images.githubusercontent.com/23515/80039166-8558ad00-853a-11ea-92e0-8554f37e24cc.png)

- Says "2 ways" but list contains 4 items, 1 crossed out
- The sublist looks like it's supposed to come after the `children` item, but it appears after the `component` item
- The yellow warning box suggests that the `component` item was supposed to be crossed out too (that would solve the "2 ways" issue)

**Comment by patspam** [comment]
Also, `<Field component />` does not "show a warning in the console".

(All of the formik-material-ui examples use `component`)

**Comment by Shakahs** [comment]
To add onto this, it seems the following needs to be updated as in V2 throwing an exception is incorrect, instead you are supposed to resolve an error string. The accompanying example code example is also wrong.

`Async: return a Promise that throws a string containing the error message. This works like Formik's validate, but instead of returning an errors object, it's just a string.`
