### ISSUE TITLE
resetForm's nextInitialState is not documented

### ISSUE THREAD

**Issue by patspam** [formium/formik#2436]
In 2.x `resetForm` takes an optional `nextInitialState` instead of just `initialValues`, however the documentation does not say what initial state (aka `FormikState`) should actually look like.

I wasted a bit of time trying `resetForm({ initialValues: {...})` etc until I discovered that it's supposed to be `resetForm({ values: {...})`

**Comment by CoreyAR** [comment]
How would you suggest the documentation could be improved?

It is a little confusing because the docs mention `initial<State>` in the description but the argument shape is actually the internal state and does not use the argument names for passing initial arguments.

If you look at the type of the shape in the docs it becomes clearer what shape the argument is
https://github.com/jaredpalmer/formik/blob/d4049f2da7e2e8811b498ea8013b77af063c6c8a/packages/formik/src/types.tsx#L39

**Comment by fourcolors** [comment]
Wow yeah this was really helpful, I would have had no clue to use `resetForm({ values: {...} })` without this issue. 

I recommend creating examples in the documentation, not just stating. Good documentation should always have the following.
1. Well written rules 
2. Well written examples with contexts for those examples
3. References to relevant information.

**Comment by MuhammadSaadQadeer** [comment]
+1 spent two and a half hour figuring out how initialState would work with resetForm, this needs an update ASAP

Thanks

**Comment by sw-yx** [comment]
i made a start on the docs https://github.com/formium/formik/pull/2743 but this does need much better docs yes

**Comment by jaredpalmer** [comment]
An object of values, errors, touched, isSubmitting
