### ISSUE TITLE
Proposal: facebook's Recoil integration for state persistence between unmounts

### ISSUE THREAD

**Issue by dvakatsiienko** [formium/formik#2493]
### Current Behavior

The form state is stored locally to component, which causes loosing state when form is unmounted.

### Desired Behavior

An option to persist form state between component mount-unmount lifeceycle with a small cost (of course avoiding something like redux-form).

### Suggested Solution

[Facebook's new state manager Recoil was introduced](https://www.youtube.com/watch?v=_ISAA_Jt9kI&t=1s) during recent React Europe event. Which is very promising. 
Integrating an option to **optionally** store form state inside of **Recoil's** atom is hugely desirable.

### Who does this impact? Who is this for?

Of course, storing form state (especially complex ones) is a widely discussed topic. That is why redux-form and others appeared on the scene. And yes it has its own problems but the time goes on, and **Recoil** may allow to solve this problem a a new less complex way but providing such a desirable feature.

### Additional context

As **Recoil** is very minimalistic and its api so, it is possible to turn on **state persistence** feature by a single flag.

```
<Formik persist initialValues = {{ ... }} ...otherProps />
```

**Comment by mentierd** [comment]
this should definitely help with useless re-renders when updating the form.

**Comment by jaredpalmer** [comment]
Storing React state in multiple places is a bad idea. It never works. Formik state can be stored in between mounts using regular react state and `setFormikState`. You can see this in the wizard example  https://github.com/formium/formik/blob/master/examples/MultistepWizard.js . You can also persist state to localStorage or sessionStorage and restore it with setFormikState as well.

**Comment by leo-terratrue** [comment]
@jaredpalmer I'm not seeing setFormikState in that wizard example (or anywhere in the docs)- Is that a part of the current public API?

**Comment by thexpand** [comment]
As far as I can see, `setFormikState` is there when I check the Formik instance, but it is missing from the documentation - it doesn't mention anything about this function.

So, my question to @jaredpalmer here is - is it safe to use it, because it is not documented at all. Someone might consider it not part of the public API and might be afraid to use it because of this.

**Comment by mentierd** [comment]
@thexpand i think it’s safe to say you can use setFormikState. I’ve used it in a few different projects over the past year. I’ve often found it most useful when you need to update something like the values and status at the same time. From my experience, it’s been around for awhile and it’s part of the types.  Formik doesn’t have the greatest documentation, so it doesn’t surprise me that it’s not in there.

**Comment by thexpand** [comment]
@mentierd Using `setFormikState` didn't work for me, it produces unpredictable results. Also, personally, I'm not okay with using something that's not documented, because it can disappear all of a sudden. What I did was that I created a local state `const [initialValues, setInitialValues] = useState(emptyValues);` to hold the initial values. Then, in a useEffect which has no dependencies, I fetch the form values from the local storage and set them via `setInitialValues`. This changes the local state `initialValues`. Having this, then I pass `initialValues` to the `useFormik` hook and make use of the `enableReinitialize: true` option, which, whenever the `initialValues` change, re-initializes Formik's state.
