### ISSUE TITLE
not setting up fields as touched on input change

### ISSUE THREAD

**Issue by Ricka7x** [formium/formik#2540]
### Reproducible example

https://codesandbox.io/s/formik-not-setting-touched-y1o8o

### environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |  2.1.4
| React            | 16.13.1
| TypeScript       |
| Browser          | Chrome  83.0.4103.106 
| npm/Yarn         | 6.14.4 / 1.15.2
| Operating System | Mac OS Catalina 10.15.4

**Comment by johnrom** [comment]
@Ricka7x you have to add a blur handler to your input, like the prop I added to the input here: 

https://codesandbox.io/s/formik-not-setting-touched-9gbo9?file=/src/App.js

Keep in mind, you can use the `Field` component to handle some magic behind the scenes. You can also use the `Formik` component instead of `useFormik()`.

https://codesandbox.io/s/formik-not-setting-touched-qsbup?file=/src/App.js

(Sorry for the spoilers if you're following the tutorial!)

**Comment by Ricka7x** [comment]
thanks so much!
