### ISSUE TITLE
Lodash duplication

### ISSUE THREAD

**Issue by ritchieanesco** [formium/formik#2602]
## 🐛 Bug report

In our bundle analyser we have picked up that both `lodash` and `lodash-es` are being imported into Formik.
https://github.com/formik/formik/blob/c238e9881e2473dccadf58246c6183ff5c17ff6b/packages/formik/package.json#L46-L47

This unnecessarily increases the file size.

### Suggested solution(s)

Remove `lodash-es` and ensure only the individual lodash utilities are imported.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4 |
| React            | 16.8.4 |
| TypeScript       | 3.7.4 |
| Browser          | Version 83.0.4103.61 (Official Build) (64-bit) |
| npm/Yarn         | 6.9.0 / 1.17.3
| Operating System | Mac OS Catalina |

**Comment by johnrom** [comment]
This is a pretty common issue, but the issue is that `lodash` itself exports CommonJS modules which webpack wraps with _extra code_ to incorporate into your ES module environment.

Formik uses `lodash-es` because it doesn't require this wrapping, meaning it is smaller. If you are using lodash in an ESM environment, you should instead do this:

```
// webpack.config.js or whatever
webpackConfig.resolve.alias = {
  lodash: 'lodash-es',
};
```

Now, every single time your project or any of its dependencies imports lodash, you'll get lodash-es (just like Formik), and lodash will never be used in your build, resulting in the smallest possible build of all the options.

```js
// with the above alias, this actually imports `lodash-es`, 
// and _only_ the shuffle function and any dependent functions
// the rest of `lodash-es` will be tree-shaken unless it is used in dependencies like Formik
import { shuffle } from 'lodash'; 

shuffle([]);
```

https://github.com/formik/formik/issues?q=is%3Aissue+lodash-es

If we did not preoptimize this, anyone who uses Formik in ESM but does not use Lodash themselves would have an oversized lodash import.
