### ISSUE TITLE
React formic conditional rendering initialValues

### ISSUE THREAD

**Issue by ChrisPotgieter** [formium/formik#2815]
I am conditionally rendering the value but the value does not display in the textfield ,only when I remove the rendering does it work
,any suggestion?

initialValues = {{
[props.entitytype === 1
                        ? 'payee'
                        : {
                                lastPaid: '',
                                lastPaidAmmount:currentEntityData.payee.lastPaidAmmount, //getting data from api
                                lastInvoiceNumber: currentEntityData.payee || '',
                          } ]:{}
}}

**Comment by clflowers5** [comment]
FYI, you can format code in markdown  and Github by using three backticks ``` ` ```. 

1. you should assign this object to a variable and log it before rendering. That's a good debugging tactic, and will likely give you more context on what's going on.

2. `//getting data from api` I don't know if you mean this is actually creating a network request, if it is React isn't going to wait for your api to return data before rendering - JavaScript is non-blocking. Do any data fetching before rendering, otherwise you'll be passing in bad data to Formik (you can observe this by following step 1 above.)

Reproducible examples are always helpful.

**Comment by ChrisPotgieter** [comment]
So do you mean create at the top var lastPaidAmmount =currentEntityData.payee.lastPaidAmmount and use that in my formik conditianal values   @clflowers5

**Comment by maddhruv** [comment]
Hey @ChrisPotgieter as I can understand with the issue, the problem is with the re-rendering of the form when the `initialValues` changes, correct me if I am wrong 🙈 

If that is the case, please try this prop - `enableReinitialize`, more info here - https://formik.org/docs/api/withFormik#enablereinitialize-boolean it can cause the form to reset with the newly provided/modified `initialValues`
