### ISSUE TITLE
regression from formik 2.1.4 -> 2.2.1

### ISSUE THREAD

**Issue by sibelius** [formium/formik#2839]
### Current Behavior

It is not handling well non memorized initial values

this does not work well

```jsx
const initialValues = {};
const formikBag = useFormik({ initialValues })
```

this works:

```jsx
const initialValues = useMemo(() => ({}), [])
const formikBag = useFormik({ initialValues })
````

it always sends the initialValues to validationSchema, check this issue https://github.com/jquense/yup/issues/1084

### Expected behavior

it should send the current values to validation schema

### Reproducible example

I'm try to make one

### Suggested solution(s)

We should try to git bisect to understand when the regression was introduced
We should also add a test to avoid this happening again

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.1
| React            | 17.0.0
| TypeScript       | 4.0.2
| Browser          | chrome
| npm/Yarn         | yarn
| Operating System | mac

**Comment by umidbekkarimov** [comment]
@sibelius  `formik@2.2.1` depends on `scheduler: '^0.18.0'`, but `react-dom` depends on `scheduler: '^0.20.0'`
Can you check your version with `yarn why scheduler` or `npx npm-why scheduler`?

**Comment by sibelius** [comment]
formik -> scheduler 0.18.0
react-dom 17 -> scheduler 0.20.0

would this be a problem?

any plan to support react-dom 17?

**Comment by umidbekkarimov** [comment]
> formik -> scheduler 0.18.0
> react-dom 17 -> scheduler 0.20.0
> 
> would this be a problem?
> 
> any plan to support react-dom 17?

I was just an assumption because I had a similar problem with `formik@2.2.0` and `react@17`, but changing `scheduler` to the same version didn't help. 
____
I was working on https://github.com/formium/formik/pull/2854 and can't say that this will fix your problem too, can you provide code sandbox reproduction?

**Comment by sibelius** [comment]
maybe related to this 
![image](https://user-images.githubusercontent.com/2005841/98043355-d9a2ea80-1e03-11eb-9f8f-613714d00c43.png)

https://github.com/formium/formik/releases/tag/v2.1.5

there were some changes on initialValues some how

**Comment by jaredpalmer** [comment]
Can you submit a PR?

On November 3, 2020, GitHub <notifications@github.com> wrote:
> maybe related to this
>  
>

> <https://github.com/formium/formik/releases/tag/v2.1.5>
>
> there were some changes on initialValues some how
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/formium/formik/issues/2839#issuecomment-721388288>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AA67IG3PIKULEA2XR6Y7MEDSOB2C7ANCNFSM4S7ISTNA>.

**Comment by umidbekkarimov** [comment]
@sibelius looks like nothing wrong in https://github.com/formium/formik/pull/2318/files, since `initialValues` should not change during rerenders when `enableReinitialize` is disabled. Here is the line where `initialValues` are updated https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L454-L457, do you pass `enableReinitialize`?

**Comment by sibelius** [comment]
I'm gonna close for now and investigate more

I do not have reInitialize flag on
