### ISSUE TITLE
To add dirty/pristine field property to 'FieldMetaProps'

### ISSUE THREAD

**Issue by StudioSpindle** [formium/formik#2909]
### Current Behavior

You have to use your own method to determine if a field has a changed value on a field level.

### Desired Behavior

To be able to check in `FieldMetaProps` whether or not the field's value has been altered.

### Suggested Solution

Do a comparison on field level to check whether or not the field is dirty/pristine. Perhaps the same method as in the comparison at form level can be used which calculates that dirty value.

### Who does this impact? Who is this for?

Everyone who wants to check whether or not a field still has the original value.

### Describe alternatives you've considered

I am using a comparison on field level in my components:

```ts
if (touched && JSON.stringify(value) !== JSON.stringify(initialValue)) {
   // this field is dirty
}
// Or better yet instead of JSON.stringify use an object-diff library for this comparison.
// Formik uses isEqual from react-fast-compare
```

**Comment by StudioSpindle** [comment]
Relates to #1364 #1421

**Comment by jaredpalmer** [comment]
+1 will add to v3.

**Comment by miquelvir** [comment]
Any update on when is this going to be available?

**Comment by radoslavius** [comment]
+1

**Comment by johnrom** [comment]
I don't think this makes sense for us to provide via the API, because different people may have different definitions for what they think dirty/pristine is. I might think it's reference equality (field value can be array or object) while another person may test for shallow equality or even deep equality.

v3 will include fieldMeta.initialValue (is this the case in v2? I don't remember) for users to test against the current value and determine equivalency.

**Comment by TamirCode** [comment]
formik is supposed to make my life easier , my code is looking extremely verbose . It makes sense to have a way to check if individual input has been modified
