### ISSUE TITLE
Trying to setTouched crashes form

### ISSUE THREAD

**Issue by kpietrzak-web** [formium/formik#3019]
### Current Behavior
When trying to use setTouched an error "Attempted to assign to readonly property" occurred in "formik.cjs"development.js(202:5)"

### Expected behavior
Can use setTouched without any errors

### Reproducible example
1. Add new custom field
2. Use `setFieldTouched` from `useFormikContext` or `setTouched` from `useField`
3. try to set true as touched

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.5
| React            | 17.0.1
| TypeScript       |
| Browser          | React Native
| npm/Yarn         | yarn
| Operating System | Android

**Comment by johnrom** [comment]
The template for opening new issues provides a codeSandbox template to reproduce your issue. It sounds like a callback is calling setFieldTouched without a name, or calling setTouched incorrectly. Or, it's just being used in a way we don't have a test case for, in which case a codesandbox will help us get right to the bottom of it.

I am constantly performing the steps in your "reproducible example" when creating new forms, and I have never run into this issue, which is why a codesandbox will help determine what is different in your case.
