### ISSUE TITLE
touched property sometimes is an object sometimes is boolean

### ISSUE THREAD

**Issue by kpietrzak-web** [formium/formik#3020]
### Current Behavior
When I'm using `touched` value from `useFormikContext` it can be an object with informaiton which fields are toucher or just boolean value
1. In case when I'm not modyifing any fields and just press send button(`handleSubmit`) I'm getting object with touched or not touched fields
2. In case when I'm editting single field I'm getting boolean in the same place

### Expected behavior
`touched` should be always object with touched fields

### Reproducible example
1. Add new custom fields in react native which use `useFormikContext`
2. Build form
3. send form without touch any fields
4. check value of `touched` from `useFormikContext`
5. Refresh screen
6. modify some field
7. checkk value of `touched` from `useFormikContext` in this field

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.1
| React Native           | 0.63.4
| TypeScript       |
| Browser          | React Native
| npm/Yarn         | yarn
| Operating System | Android

**Comment by johnrom** [comment]
@kpietrzak-web can you provide a codesandbox? I've never heard of anything like this. It sounds likely that some component is calling `formik.setTouched` with the wrong value. `useField()` is the only callback which generally returns a `boolean` for touched, because it will return whether the current Field is touched.
