### ISSUE TITLE
How can I put a counter input value in the Formik array values

### ISSUE THREAD

**Issue by mariamahmed9** [formium/formik#3086]
I have problem when I submit my data the counter value isn’t in the array data it is always counter=0
This is my code in the sandbox https://codesandbox.io/s/lucid-rgb-tj89d?file=/src/index.js

**Comment by mhamzaasif** [comment]
There is an issue with your implementation of the form. So far you are expecting the counter value to be submitted with the form. Let's get into some basic flow of the formik. Formik manages an `internal state` against all the fields of the form. If you see the screenshot below you are passing counter state value directly in the field value that's why it is showing counter in the form. but `onChange` you are setting counter state value not the form state. or in other words, you are not using the `handleChange` method of the `formik` that's why it is not updating the internal state thus we are not getting counter with the submitted form.
<img width="724" alt="Screenshot 2021-04-15 at 7 35 41 PM" src="https://user-images.githubusercontent.com/26824434/114887505-f36c4300-9e21-11eb-8670-4baaa7dcd40d.png">

**Comment by johnrom** [comment]
I'd remove counter from `values` entirely and combine `values` and the counter object during the submit function to a new object via spread.

```tsx
onSubmit={values => doSubmit({ 
  ...values, 
  counter,
});
```

This way you avoid mutating the values within Formik.
