### ISSUE TITLE
resetForm ignores passed values when enableReinitialize is on

### ISSUE THREAD

**Issue by ryym** [formium/formik#3129]
### Current Behavior

The `resetForm` function ignores the passed new values and keeps using `initialValues`, only when the `enableReinitialize` is set to true.

```js
formik.resetForm({ values: newValues });
```

### Expected behavior

The `resetForm` function updates the values regardless of `enableReinitialize`.

### Reproducible example

<https://codesandbox.io/s/formik-resetform-bug-repro-dpbkg>

1. Open the page.
2. Click the `Set new values` button.
3. Confirm that the input value does not be updated.

If you disable `enableReinitialize`, the input value is updated to the specified new value.

### Suggested solution(s)

Formik should use the new `values` passed to `resetForm`.

### Additional context

I found some issues which may be related:

- https://github.com/formium/formik/issues/2689
- https://github.com/formium/formik/issues/2440
- https://github.com/formium/formik/issues/2034
- https://github.com/formium/formik/issues/1819

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.2
| TypeScript       | Unused
| Browser          | Google Chrome Version 89.0.4389.114
| npm/Yarn         | Yarn 1.22.10
| Operating System | macOS Catalina 10.15.7

**Comment by ryym** [comment]
I found that the cause is this effect:
https://github.com/formium/formik/blob/2d613c11a67b1c1f5189e21b8d61a9dd8a2d0a2e/packages/formik/src/Formik.tsx#L414-L434

This effect has `props.initialValues` in the dependency list and set it to `initialValues.current` on its change if `enableReinitialize` is true (L419 ~ L421). 
So if we use the `useFormik` hook like following, the effect resets `initialValues` after every render, because `initialValues` is recreated in every render.

```jsx
const formik = useFormik({
  enableReinitialize: true,
  initialValues: { foo: "hello" },
})
```

Therefore we can avoid this problem by using the same `initialValues` object in every render.
Example: https://codesandbox.io/s/formik-resetform-bug-repro-workaround-cn0w9

**Comment by johnrom** [comment]
Seems like this is working as expected. This allows you to both use resetForm() and initialValues() to trigger updates.

**Comment by ryym** [comment]
Sorry, my previous comment https://github.com/formium/formik/issues/3129#issuecomment-812467479 was incorrect so I updated it.

> Seems like this is working as expected.

Hmm, I think this is not an intended behavior because normally `enableReinitialize` works without the referential equality of `initialValues`.
It would be nice if `enableReinitialize` works consistently with `resetForm({ values })`.

**Comment by johnrom** [comment]
- initialValues uses a deep equality check `isEqual` because it's common (bad, but common) practice to create a "new object" on every render, like: `initialValues={{ firstName: '' }}`.
- resetForm doesn't need to do these kinds of checks. it's possible someone would want resetForm to be triggered even if the object are "deeply equal" to make `initialValues` referentially equal the `values` object.

Your problem is definitely because of the useFormik hook. The Formik component wouldn't have this problem. The particular combination Formik uses is the only way to allow you to use `resetForm` and then later update your `initialValues` with enableReinitialize (the only props which will trigger its effect are enableReinitialize and initialValues).

If you memoize initialValues, it will fix your issue with useFormik. I think we can add a note on the useFormik documentation about this, since it will happen with any combination of useFormik + resetForm.

**Comment by ryym** [comment]
> I think we can add a note on the useFormik documentation about this

Agree!
I think the current behavior is not a problem if the document has a description about this. Thank you.

**Comment by Yair-Ohana** [comment]
This is not solved and can be reproduces with `<Formik>` as well ..
