### ISSUE TITLE
The code in `<formik>` will be re-render twice, and the `initialValues` output by the first rendering is different from the external first

### ISSUE THREAD

**Issue by liby** [formium/formik#3334]
### Current Behavior

The code in `<formik>` will be re-render twice, and the `initialValues` output by the first rendering is different from the external one.

### Expected behavior

Render only once and get the correct value.

### Reproducible example

https://codesandbox.io/s/vigorous-grass-p3pn4

### Suggested solution(s)

Not yet.

### Additional context

![image](https://user-images.githubusercontent.com/38807139/132329753-6375839b-6bf8-4408-9ff8-e157ef60bc04.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.2.9 |
| React            | ^17.0.2 |
| TypeScript       | 4 |
| Browser          | Chrome 92.0.4515.159 |
| npm/Yarn         | 1.22.10 |
| Operating System | macOS 11.2.1 |

**Comment by johnrom** [comment]
This is expected behavior, as the values Formik accepts as initialValues should not be considered its internal initialValues. When you update initialValues, Formik checks whether it changed during an effect, and if so it updates its own initialValues as well as optionally performing other operations, like reinitialize. Think about it this way:

On the initial render, if you logged initialValues and values, you'd expect to see:

```js
// sourceInitialValues = values1
{
  initialValues: values1,
  values: values1,
}
```

Then on the second "render", if you updated initialValues, you'd expect to see:

```js

// sourceInitialValues = values2
{
  initialValues: values2,
  values: values2,
}
```

The issue you're seeing, is that due to the way React works, there is a second render between them, which is inconsequential when your code adheres to the rules of React (side effects take place within effects, not render), as well as considers Formik's state independently as the single source of truth of its own state.

```js
// render
// sourceInitialValues = values1
{
  initialValues: values1,
  values: values1,
}
// render
// sourceInitialValues = values2
{
  initialValues: values1,
  values: values1,
}
// render
// sourceInitialValues = values2
{
  initialValues: values2,
  values: values2,
}
```

If the opposite were to be true and formik.initialValues were to read as the updated value of the source, you would actually get a torn snapshot of what Formik's state looks like.

```
{
  initialValues: values2,
  values: values1,
  isDirty: true, // dirty is actually never true in this scenario, but now initialValues doesn't equal values.
}
```

**Comment by johnrom** [comment]
You can see how you could access this correctly from the parent like this:

https://codesandbox.io/s/elegant-dew-k5bqv?file=/src/index.tsx

(this uses a v3 PR but you can get initialValues and values directly from `useFormik` in v2)

**Comment by liby** [comment]
I think I know what you mean, but there seems to be something wrong with the example you gave.
![image](https://user-images.githubusercontent.com/38807139/132377609-ba749f51-d667-4a1b-b349-5573c6e372b5.png)

**Comment by johnrom** [comment]
Seems like a bug with codesandbox because I changed the example from there.

**Comment by liby** [comment]
Wow, You seem to use formik in a way I've never seen before. I will study it carefully. If there is a problem, we are communicating. Have a nice day.

**Comment by johnrom** [comment]
This method isn't thoroughly documented for v2 since we weren't sure whether React would continue working with useFormik+Provider or if we'd have to optimize within the Formik component. however it turns out we can optimize within useFormik / FormikProvider and thus we'll document this method whenever v3 is released

**Comment by liby** [comment]
The code example I provided earlier is a bit messy, with irrelevant libraries such as Jotai. It is easier to be disturbed when checking the code. According to your example, I wrote a version based on `useState` + Formik v3. v3 works fine, but is this use of multiple layers of Hook nesting a bit counter-intuitive? It always feels like it's not simple enough.

**Comment by johnrom** [comment]
I prototyped dozens of ways to make this work, and unfortunately this was the only one which made any sense and worked everywhere (both inside and outside of React context).

This is only necessary outside of context when using the return value of useFormik, as the hook useFormikState (is the same thing as useFormikContext().useState()) is provided when Context is available.

In terms of the selector itself, it can be a constant function instead of using useCallback.

If you look around the React ecosystem, you'll see all kinds of growing pains with React hooks, and many libraries like Redux deal with the same thing. Redux however is global to the application, so it never has to expose functionality to components above it in the hierarchy like Formik often does. If it did, it would be just as counterintuitive.
