### ISSUE TITLE
Values is change from array to object

### ISSUE THREAD

**Issue by kirusick** [formium/formik#936]
If set array to initialValues. Values in props is array, but after changing values set to object.

Example: https://codesandbox.io/s/766rn18vx

**Comment by yuritoledo** [comment]
Check the console.log, in this sandbox https://codesandbox.io/s/00joz167qv

The error happens because your dynamic `name` prop. You should fix this, because it (name) changes when `handleChange` is called.

**Comment by luke-dare** [comment]
I've noticed the same for the errors array. Is this a recent breaking change?

**Comment by yuritoledo** [comment]
I dont know :/

Why you dont use the `withFormik` HoC ? Is simpler and cleaner than the approch callbackFunction.

**Comment by ksmolniy** [comment]
@yuritoledo It don't work in all cases https://codesandbox.io/s/qz67j14vvq
Somebody from maintainers read issues?

**Comment by yuritoledo** [comment]
@ksmolniy this example can help you?

https://codesandbox.io/s/x713mjnkk4

**Comment by vadistic** [comment]
I just wanted to let you know it still happens in `2.0.0-gamma.1`

Arrays in nested initalValues get converted to number indexed objects.

It makes difference, because with current output `Array.isArray(values.arrayProp) = false` and it can break a lot of logic. I'm running some `deepNormaliseBackToArrays` function on each submit payload, but this in turn probably negates a lot optimisation done in formik.

Also `useFormik` has no api like `mapPropsToValues` so I need it to do it in custom wrapper.

It may be worth to take a look at :wink:

**Comment by jaredpalmer** [comment]
initialValues cannot be an array.

**Comment by maddhruv** [comment]
Hey @kirusick I hope this is no more valid, as `initialValues` need to have at least one `key:value` pair, that refers to any of the `Fields`

e.g. `initialValues={{foo: 'bar'}}`
